global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: koomky_app
    metrics_path: /metrics
    static_configs:
      - targets:
          - nginx:80

  - job_name: postgres_exporter
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: redis_exporter
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: node_exporter
    static_configs:
      - targets:
          - node-exporter:9100
